
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def fibonnaci_even(limit)
  fibonnacci = [1, 1]
  (1...limit).each { fibonnacci << fibonnacci.last(2).sum }
  fibo_even = fibonnacci.select { |num| num.even? }.sum
end
  
puts fibonnaci_even(1000)
